language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11

branches:
  only:
    - master

services:
  - redis-server

addons:
  postgresql: "9.4"

install:
  - cd conf
  - mv settings_local.py.txt settings_local.py
  - cd ..
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - export MUSS_DB_HOST="127.0.0.1"
  - export MUSS_DB_PORT="5432"
  - export MUSS_DB_USER="postgres"
  - export MUSS_DB_PASSWORD=""
  - export MUSS_DB_NAME="muss"

script:
  - coverage run --source=muss manage.py test

after_success:
  coveralls